-   id: blacken-docs
    name: blacken-docs
    description: Run `black` on python code blocks in documentation files
    entry: blacken-docs
    language: python
    language_version: python3
    files: '\.(rst|md|markdown|tex)$'
